#!/bin/bash
cd .packaging/linux
mkdir -p DungeonsEditor.AppDir/usr/bin
mkdir -p DungeonsEditor.AppDir/usr/lib
mkdir -p DungeonsEditor.AppDir/usr/share/icons/hicolor/256x256/apps

cp -r ../../build/compose/binaries/main-release/app/DungeonsEditor DungeonsEditor.Built
cp -r DungeonsEditor.Built/bin/DungeonsEditor DungeonsEditor.AppDir/usr/bin
cp -r DungeonsEditor.Built/lib/* DungeonsEditor.AppDir/usr/lib/
cp DungeonsEditor.Built/lib/DungeonsEditor.png DungeonsEditor.AppDir/usr/share/icons/hicolor/256x256/apps/DungeonsEditor.png
cp DungeonsEditor.Built/lib/DungeonsEditor.png DungeonsEditor.AppDir

chmod +x DungeonsEditor.AppDir/AppRun

wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
chmod +x appimagetool-x86_64.AppImage

./appimagetool-x86_64.AppImage DungeonsEditor.AppDir DungeonsEditor.AppImage