name: Package Release Distribution

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: "version name"
        required: true

jobs:

  package-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Setup main repository
        uses: actions/checkout@v4

      - name: Setup PakReader
        uses: actions/checkout@v4
        with:
          repository: hoonkun/PakReader
          token: ${{ secrets.PAK_READER_ACCESS_SECRET }}

      - name: Create Keysets
        run: echo "${{ secrets.KEYSET }}" > ./src/jvmMain/kotlin/Keyset.kt

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Hello, LINUX World!
        run: echo Hello, LINUX World!

      - name: Gradle Build
        run: ./gradlew build

      - name: Package Linux
        run: ./gradlew packageReleaseDistributionForCurrentOS

      - name: Build AppImage
        run: |
          chmod +x .packaging/linux/prepare-appimage
          .packaging/linux/prepare-appimage

      - uses: actions/upload-artifact@v4
        with:
          name: "DungeonsEditor-${{ github.event.inputs.version_name }}.AppImage"
          path: .packaging/linux/DungeonsEditor.AppImage

  package-windows:
    runs-on: windows-latest

    steps:
      - name: Setup main repository
        uses: actions/checkout@v4

      - name: Setup PakReader
        uses: actions/checkout@v4
        with:
          repository: hoonkun/PakReader
          token: ${{ secrets.PAK_READER_ACCESS_SECRET }}

      - name: Create Keysets
        run: echo "${{ secrets.KEYSET }}" > ./src/jvmMain/kotlin/Keyset.kt

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Hello, WINDOWS World!
        run: echo Hello, WINDOWS World!

      - name: Gradle Build
        run: ./gradlew build

      - name: Package Windows
        run: ./gradlew packageReleaseDistributionForCurrentOS

      - name: Post Package - Extract and Archive
        run: tar -a -c -f .packaging/windows/DungeonsEditor.zip -C "./build/compose/binaries/main-release/app/DungeonsEditor" .

      - uses: actions/upload-artifact@v4
        with:
          name: "DungeonsEditor-${{ github.event.inputs.version_name }}.zip"
          path: .packaging/windows/DungeonsEditor.zip

