name: Package Release Distribution

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: "version name"
        required: true

jobs:

  package-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Dependencies
        run: |
          sudo apt update
          sudo apt install -y libfuse2

      - name: Set up DungeonsEditor
        uses: actions/checkout@v4
        with:
          path: ${{github.workspace}}/DungeonsEditor

      - name: Set up PakReader
        uses: actions/checkout@v4
        with:
          repository: hoonkun/PakReader
          path: ${{github.workspace}}/PakReader
          token: ${{ secrets.PAK_READER_ACCESS_SECRET }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Keysets.kt
        working-directory: ${{github.workspace}}/DungeonsEditor
        run: echo "${{ secrets.KEYSET }}" > ./src/jvmMain/kotlin/Keyset.kt

      - name: Gradle Build
        working-directory: ${{github.workspace}}/DungeonsEditor
        run: ./gradlew build

      - name: Gradle Package Release
        working-directory: ${{github.workspace}}/DungeonsEditor
        run: ./gradlew packageReleaseDistributionForCurrentOS

      - name: Bundle AppImage
        working-directory: ${{github.workspace}}/DungeonsEditor
        run: |
          chmod +x .packaging/linux/prepare-appimage
          .packaging/linux/prepare-appimage

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "DungeonsEditor-${{ github.event.inputs.version_name }}.AppImage"
          path: ${{github.workspace}}/DungeonsEditor/.packaging/linux/DungeonsEditor.AppImage

  package-windows:
    runs-on: windows-latest

    steps:
      - name: Set up DungeonsEditor
        uses: actions/checkout@v4
        with:
          path: ${{github.workspace}}/DungeonsEditor

      - name: Set up PakReader
        uses: actions/checkout@v4
        with:
          repository: hoonkun/PakReader
          path: ${{github.workspace}}/PakReader
          token: ${{ secrets.PAK_READER_ACCESS_SECRET }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Keysets.kt
        working-directory: ${{github.workspace}}/DungeonsEditor
        run: echo "${{ secrets.KEYSET }}" > ./src/jvmMain/kotlin/Keyset.kt

      - name: Gradle Build
        working-directory: ${{github.workspace}}/DungeonsEditor
        run: ./gradlew build

      - name: Gradle Package Release
        working-directory: ${{github.workspace}}/DungeonsEditor
        run: ./gradlew packageReleaseDistributionForCurrentOS

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "DungeonsEditor-${{ github.event.inputs.version_name }}"
          path: ${{github.workspace}}/DungeonsEditor/build/compose/binaries/main-release/app/DungeonsEditor

