name: package-release-setup
on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      label:
        required: true
        type: string

jobs:
  setup:
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Setup main repository
        uses: actions/checkout@v4

      - name: Setup PakReader
        uses: actions/checkout@v4
        with:
          repository: hoonkun/PakReader
          path: PakReader

      - name: Create Keysets
        run: echo "${{ secrets.KEYSET }}" > ./src/jvmMain/kotlin/Keyset.kt

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Hello, ${{ inputs.label }} World!
        run: echo Hello, ${{ inputs.label }} World!

      - name: Gradle Build
        run: ./gradlew build
